export * from './element.interface'
export * from './employee.abstract-element'
export * from './manager.element'
export * from './programmer.element'
export * from './salary.visitor'
export * from './seniority.visitor'
export * from './visitor.interface'
export * from './sample'
